### ISSUE TITLE
implement a smaller time span until device turns on and off

### ISSUE THREAD

**Issue by Smurfsmurfsmurf** [InventoCasa/ha-advanced-blueprints#10]
I have got certain devices I want to turn on and off immediately if there is enough / not enough solar power.
Therefore it would be great to have the option setting the "appliance on/off switch intervall to 0 or to some seconds.

**Comment by InventoCasa** [comment]
Unfortunately I decided against implementing this for now, since I do not see big usecases for the typical home owner. An interval of 1 Minute should be fast enough for now.
One thing I did however, was to improve the excess approximation by calculating the average excess every 10s (now) instead of every minute (before). On days with fast switching between clouds/sun, this should improve the general ability of the algorithm to approximate the available PV excess.
