### ISSUE TITLE
Using template_number for setting "Appliance SetCurrent entity"

### ISSUE THREAD

**Issue by Smurfsmurfsmurf** [InventoCasa/ha-advanced-blueprints#14]
Heyho
It would be much easier to be able using template_numbers for setting an appliance SetCurrent.

**Comment by InventoCasa** [comment]
Hi,

I think what you meant - at least that's what we discussed previously - are not _template number_ entities. 
Because that already works since template number entities are normal number entities.

What you meant were **_input_number_** entites.
To be able to pass these, I implemented a new function to dynamically call a service based on its domain.
So, input_number entities should work now.
