### ISSUE TITLE
Could not get state from entity automation…

### ISSUE THREAD

**Issue by finalbillybong** [InventoCasa/ha-advanced-blueprints#21]
After installing and setting up the blueprints for three of my appliances I get the following error in my logs.

`This error originated from a custom integration.

Logger: custom_components.pyscript.file.pv_excess_control.on_time
Source: custom_components/pyscript/eval.py:1901
Integration: Pyscript Python scripting (documentation, issues)
First occurred: 20:57:00 (3 occurrences)
Last logged: 20:57:00

Could not get state from entity automation.start_dish_washer_solar_excess: name 'automation.start_dish_washer_solar_excess' is not defined
Could not get state from entity automation.start_washing_machine_solar_excess: name 'automation.start_washing_machine_solar_excess' is not defined
Could not get state from entity automation.start_tumble_dryer_solar_excess: name 'automation.start_tumble_dryer_solar_excess' is not defined`

The name of my automation(s) matches the blueprint(s) as required.

![D482236E-5180-4B6C-B455-DA929B3F4564](https://user-images.githubusercontent.com/24855560/232893204-1a34d5ec-eb0a-450f-90fa-701574e7a6ea.png)
![B5ABD346-3AF7-4E21-8C78-CF63DBDC5179](https://user-images.githubusercontent.com/24855560/232893211-a61f10bf-69be-4fa2-8815-a5e423c710a1.png)

**Comment by InventoCasa** [comment]
Hi there, 

most likely you did save the automation, and after saving it, you changed the name of the automation. This leads to the *friendly name* of the automation being changed, but **not the entity_id**.

And since the script looks for the entity id (automation.[...]) it cannot find it because it differs from the *friendly name*

You can verify this by opening your automation, clicking on the three dots, and navigating to something like "more info --> settings" or similar. There you can see the **entity_id** of the automation and compare it to what you have written into the *automation name* field of the blueprint.

**Comment by finalbillybong** [comment]
Yes you were absolutely correct. I have updated the entity_id’s and the error is gone. Thanks

**Comment by InventoCasa** [comment]
Happy to help! Remember to execute your automations once after changing the entity_id.
