### ISSUE TITLE
Combined consumption/production sensor

### ISSUE THREAD

**Issue by blackbird0589** [InventoCasa/ha-advanced-blueprints#6]
Hi Henrik, your project is exactly what I was looking forward so long.
I just had a look to your blueprint and for my configuration (and probably most of users with different inverters) there is the problem that we use smartmeters/powersensors for eg. Shelly 3em that gives one sensor for grid power (delivery=negative value / consumption= pos. val.), one for pv-production and one for storage.
Your blueprints description says for delivery/export "must not be negative". Is there any way to create a choice for a combined sensor for grid direction as a base for automation?
Thanks and regards

**Comment by InventoCasa** [comment]
Hello @blackbird0589, that's a good idea which was also mentioned by some other users. 
That's why I took some time today to implement this!

Now, if you don't have a hybrid inverter with battery and thus not have the separate sensors available, you will only need two sensors:
- PV Power sensor
- Combined import/export power sensor

**Comment by blackbird0589** [comment]
Wow, that was an unexpected quick solution! Thank you very much for your time and support!
