### ISSUE TITLE
Include Solar Forecast data

### ISSUE THREAD

**Issue by CommanderROR9** [InventoCasa/ha-advanced-blueprints#9]
To make this system even more useful,  adding a solar forecast feature from either Forecast Solar or Solcast might be helpful.
Solcast is especially well suited because it offers a 7 Day forecast,  reasonably accurate predictions and a "today remaining"  forecast.
This allows appliances like AC or a heat pump to run in parallel with a solar storage battery without the danger of ending up with a less-than-full battery when the sun goes down or your deferrable loads only starting to run when the home battery is full and thus only having 2-3 hours of operation time and not being able to soak up all the excess power.

**Comment by InventoCasa** [comment]
@CommanderROR9 I've got good news for you - I implemented this yesterday.
You can now pass the *today remaining forecast* from solcast (as well as your *home battery capacity*), and the script will handle the rest:
- The target for the *minimum battery level* is now the end of the day
- That means your loads will turn on right away when there is enough solar power in the morning
- the remaining "non-full" battery capacity is constantly checked again the remaining solar forecast. In case the optimizer detects that the window for charging the remaining battery capacity gets to narrow at the end of the day, it will turn off your controlled appliances so that the battery can charge to the specified *minimum battery level*
